################################################################################
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

bpdm:
  security:
    # Allowed origins for CORS
    cors-origins: '*'
    # Whether endpoints should be authenticated/authorized
    enabled: true
    # Base-URL including protocol of the Keycloak server
    auth-server-url: http://localhost:8180
    # URL to the auth endpoint of the Keycloak server
    auth-url: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}/protocol/openid-connect/auth
    # This application's resource or client. Used for finding permissions in the given Bearer token
    client-id: BPDM-POOL
    # The keycloak realm to consider
    realm: CX-Central
    # URL to the token refresh endpoint of the Keycloak server
    refresh-url: ${bpdm.security.token-url}
    # URL to the token validation endpoint of the Keycloak server
    token-url: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}/protocol/openid-connect/token
    permissions:
      # Name of the permission to read business partners
      readPartner: read_partner
      # Name of the permission to upsert business partners
      writePartner: write_partner
      # Name of the permission to read business partners that belong to a Catena-X member
      readMemberPartner: read_partner_member
      # Name of the permission to read metadata
      readMetaData: read_metadata
      # Name of the permission to create new metadata
      writeMetaData: write_metadata
      # Name of the permission to read changelog entries from business partners
      readChangelog: read_changelog
      # Name of the permission to read changelog entries from Catena-X member business partners
      readMemberChangelog: read_changelog_member

#
# From here on are framework and dependency configuration
# More information about those properties can be taken from the respective documentation of Spring or the dependency
#
spring:
  security:
    oauth2:
      resourceserver:
        # Infer the uris for token validation from the application's security properties
        jwt:
          issuer-uri: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}
          jwk-set-uri: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}/protocol/openid-connect/certs
