apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
      {{- include "bpdm.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: catenax-bpdm-dev.demo.catena-x.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bpdm.fullname" . }}
            port:
              number: {{ .Values.service.port }}