apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
      {{- include "bpdm.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - catenax-bpdm-dev.demo.catena-x.net
      secretName: {{ include "bpdm.fullname" . }}-tls
  rules:
  - host: catenax-bpdm-dev.demo.catena-x.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bpdm.fullname" . }}
            port:
              number: {{ .Values.service.port }}