apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
      {{- include "bpdm.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuerName }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "bpdm.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bpdm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}