apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bpdm.imagePullSecretsName" . }}
data:
  {{- $ps := .Values.imagePullSecrets }}
  {{- $reg := required "docker registry is required" .Values.image.registry }}
  {{- $user := required "pull secret user is required" $ps.user }}
  {{- $pass := required "pull secret password is required" $ps.password }}
  .dockerconfigjson: {{ printf (.Files.Get "config/dockerconfig.json") $reg $user $pass ($ps.mail | default "") (include "bpdm.dockerAuth" .) | b64enc }}
type: kubernetes.io/dockerconfigjson