bpdm-gate:
  enabled: true
  postgres:
    # use the name that was override on postgres.fullnameOverride to be used by the application on connection
    fullnameOverride: ""

bpdm-pool:
  enabled: true
  opensearch:
    enabled: true
    masterService: ""
    fullnameOverride: "bpdm-pool-opensearch"
  postgres:
    # use the name that was override on postgres.fullnameOverride to be used by the application on connection
    fullnameOverride: ""

bpdm-bridge-dummy:
  enabled: true
  postgres:
    # use the name that was override on postgres.fullnameOverride to be used by the application on connection
    fullnameOverride: ""

bpdm-cleaning-service-dummy:
  enabled: true

bpdm-orchestrator:
  enabled: true


opensearch:
  masterService: ""
  fullnameOverride: "bpdm-pool-opensearch"
  enabled: true
  replicas: 1
  protocol: http
  roles:
    - master
    - ingest
    - data
  resources:
    limits:
      cpu: 300m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  config:
    opensearch.yml: |
      network.host: 0.0.0.0
      plugins.security.disabled: true
  securityConfig:
    enabled: false
  extraInitContainers:
    - name: sysctl
      image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
      imagePullPolicy: "IfNotPresent"
      command:
        - /bin/bash
        - -ec
        - |
          CURRENT=`sysctl -n vm.max_map_count`;
          DESIRED="262144";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w vm.max_map_count=262144;
          fi;
          CURRENT=`sysctl -n fs.file-max`;
          DESIRED="65536";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w fs.file-max=65536;
          fi;
      securityContext:
        runAsUser: 0
        privileged: true

postgres:
  # override the name of the postgres deploy
  fullnameOverride: ""
  enabled: true
  auth:
    database: bpdm
    username: bpdm
