bpdm-gate:
  enabled: true
  postgres:
    # use the name that was override on postgres.fullnameOverride to be used by the application on connection
    fullnameOverride: ""

bpdm-pool:
  enabled: true
  postgres:
    # use the name that was override on postgres.fullnameOverride to be used by the application on connection
    fullnameOverride: ""

bpdm-bridge-dummy:
  enabled: true
  postgres:
    # use the name that was override on postgres.fullnameOverride to be used by the application on connection
    fullnameOverride: ""

bpdm-cleaning-service-dummy:
  enabled: true

bpdm-orchestrator:
  enabled: true

postgres:
  # override the name of the postgres deploy
  fullnameOverride: ""
  enabled: true
  auth:
    database: bpdm
    username: bpdm
