# Default values for bpdm-elastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.elastic.co
  repository: elasticsearch/elasticsearch
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

discoveryType: single-node

nameOverride: ""
fullnameOverride: ""


securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000

resources:
  limits:
    cpu: 500m
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 4Gi