apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bpdm-postgres.fullname" . }}
  labels:
    {{- include "bpdm-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi