{{- if .Values.applicationSecret.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bpdm.applicationSecret.name" . }}
type: Opaque
stringData:
  cdq-key: {{ .Values.applicationSecret.cdq }}
  keycloak-secret: {{ .Values.applicationSecret.keycloak }}
{{- end }}