image:
  tag: "main"

springProfiles:
  - int

ingress:
  hosts:
    - host: partners-gate.int.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - partners-gate.int.demo.catena-x.net

applicationSecret:
  cdq: <path:bpdm/data/int/gate/cdq#api-key>