replicaCount: 1

image:
  pullPolicy: Always
  tag: "latest"

#Spring profiles under which the application should run
springProfiles:
  - dev

applicationSecrets:
  db-user: BPDM_DB_USER
  db-pass: BPDM_DB_PASS
  keycloak-secret: BPDM_KEYCLOAK_SECRET
  cdq-key: BPDM_CDQ_KEY

elastic:
  enabled: true

postgres:
  enabled: true