# Default values for bpdm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: cxtsiacr.azurecr.io
  repository: catena-x/bpdm
  pullPolicy: IfNotPresent

#Spring profiles under which the application should run
springProfiles: []

applicationSecrets:
  name: dev-bpdm-application
  mappings: { }

nameOverride: ""
fullnameOverride: ""

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000

service:
  type: ClusterIP
  port: 8080

ingress:
  issuerName: letsencrypt-prod
  host: catenax-bpdm-dev.demo.catena-x.net

elastic:
  enabled: false

postgres:
  enabled: false

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi

