apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
      {{- include "bpdm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end}}
      secretName: tls-secret
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bpdm.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end}}