apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
     {{- include "bpdm.labels" . | nindent 4 }}
data:
  dependency.yml: |-
    # Configures the application to connect to dependent services
    # These properties may be overwritten in the external.yml which is loaded afterwards
    bpdm:
        datasource:
                host: {{ include "bpdm.postgresDependency" . }}
        opensearch:
                host: {{ include "bpdm.opensearchDependency" . }}
  external.yml: |-
    # External properties for overwriting application config
    {{- if .Values.applicationConfig }}
    {{- .Values.applicationConfig | toYaml | nindent 4 }}
    {{- end }}