apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
     {{- include "bpdm.labels" . | nindent 4 }}
data:
  deployment.yml: |-
    # Place for putting standard deployment configuration which can be overwritten by external.yml
    bpdm:
      datasource:
        host: {{ include "bpdm.postgresDependency" . }}
      opensearch:
        host: {{ include "bpdm.opensearchDependency" . }}
  external.yml: |-
    # External properties for overwriting application config
    {{- if .Values.applicationConfig }}
    {{- .Values.applicationConfig | toYaml | nindent 4 }}
    {{- end }}