apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bpdm.fullname" . }}
type: Opaque
stringData:
  secrets.yml: |-
    # Secret properties for overwriting application config
    {{- if .Values.applicationSecrets }}
    {{- .Values.applicationSecrets | toYaml | nindent 4 }}
    {{- end }}