################################################################################
# Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

# Change default port since 8080 is reserved for pool
server:
    port: 8081

bpdm:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'

    # Configuration specific to the service logic
    bpn:
        agency-name: Catena-X
        id: CX_BPN
        name: Business Partner Number
        owner-bpn-l: '# Insert owner BPNL here'
    api:
        upsert-limit: 100

    # Configuration for golden record tasks
    tasks:
        creation:
            fromSharingMember:
                batchSize: 100
                cron: '-'
            fromPool:
                batchSize: 100
                cron: '-'
        check:
            batchSize: 100
            cron: '-'

    # Connection to the pool and orchestrator  [No auth on default]
    client:
        orchestrator:
            base-url: http://localhost:8085
            security-enabled: false
        pool:
            base-url: http://localhost:8080
            security-enabled: false

    # No security on default
    security:
        enabled: false

    # Datasource host
    datasource:
        host: localhost

# Logging Configuration
logging:
    unknown-user: Anonymous
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %green([%-10.10X{user:-System}]) %magenta([%-10.10X{request:-No Request}]) %yellow([%-15.15t]) %cyan(%-40.40logger{39}) : %m%n%wEx"
    level:
        root: INFO
        org:
            eclipse:
                tractusx:
                    bpdm:
                        gate: DEBUG

# Enable actuator endpoints
management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

# Datasource configuration
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ''
        url: jdbc:postgresql://${bpdm.datasource.host}:5432/bpdm
        username: bpdm
    # Flyway configuration
    flyway:
        enabled: true
        schemas: bpdmgate
    # Send updates and inserts out in batches to decrease network connections to the database
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: bpdmgate
                jdbc:
                    batch_size: 16
                order_inserts: true
                order_updates: true

# Springdoc swagger configuration
springdoc:
    api-docs:
        path: /docs/api-docs
    swagger-ui:
        csrf:
            enabled: true
        disable-swagger-default-url: true
        path: /ui/swagger-ui
        show-common-extensions: true





