name: Build Docker Image

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  containerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Build Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build Bpdm Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./gpdm/Dockerfile
          push: false

      - name: Build Wrapper Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./gpdm-wrapper/Dockerfile
          push: false