name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    tags:
      - '*'

jobs:
  call-execute-tests:
    uses: ./.github/workflows/execute-tests.yaml
    secrets: inherit

  call-release-pool:
    needs: [ call-execute-tests ]
    uses: ./.github/workflows/release.yaml
    with:
      imageName: pool
      dockerfilePath: ./bpdm-pool/Dockerfile

  call-release-gate:
    needs: [ call-execute-tests ]
    uses: ./.github/workflows/release.yaml
    with:
      imageName: gate
      dockerfilePath: ./bpdm-gate/Dockerfile