name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    tags:
      - '*'

jobs:
  call-sonar-scan:
    uses: ./.github/workflows/sonar-scan.yaml
    secrets: inherit

  call-release-pool:
    needs: [ call-sonar-scan ]
    uses: ./.github/workflows/release.yaml
    with:
      imageName: pool
      dockerfilePath: ./bpdm-pool/Dockerfile

  call-release-gate:
    needs: [ call-sonar-scan ]
    uses: ./.github/workflows/release.yaml
    with:
      imageName: gate
      dockerfilePath: ./bpdm-gate/Dockerfile