name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop

jobs:
  call-sonar-scan:
    uses: ./.github/workflows/sonar-scan.yaml
    secrets: inherit

  call-release-bpdm:
    needs: [call-sonar-scan]
    uses:  ./.github/workflows/release.yaml
    with:
      imageName: bpdm
      dockerfilePath: ./gpdm/Dockerfile

  call-release-wrapper:
    needs: [call-sonar-scan ]
    uses: ./.github/workflows/release.yaml
    with:
      imageName: bpdm-wrappper
      dockerfilePath: ./gpdm-wrapper/Dockerfile